### ISSUE TITLE
Any updates?

### ISSUE THREAD

**Issue by jwijenbergh** [loki7990/A-Setting-Spring#1]
Sorry for contacting you here, but I liked your rice in the wmutils opt issue thread. Can you share your updated bar configuration?

**Comment by loki7990** [comment]
Hello! Sorry it took me a bit to get back to you, but this is an ancient
repository for an old rice. I've just made a new one for my latest setup
here: https://github.com/loki7990/Tranquility . Let me know if you have any
questions! My dots are an absolute mess so I apologize for that

**Comment by jwijenbergh** [comment]
Thanks! I was interested in how you got two borders to work with polybar. So it seems that you're using different instances, smart!

**Comment by loki7990** [comment]
Yep! One bar has the border and contains all of the modules that I wanted, but is completely transparent. Another bar just below it is totally empty but is just slightly larger to give the illusion of double borders! Sometimes the launch script doesn't launch them in wuite the right order; the blank bar will be above the main bar. Usually refreshing the bars with the scripts will eventually yield the right order of the main bar then the blank bar launching. I may need to tweak the launch script to get it quite right at some point, but for now its functional!
